version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5431:5432"
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ../server/db/postgres/migrations:/app/server/db/postgres/migrations
    command: ["-path", 
              "/app/server/db/postgres/migrations", 
              "-database", 
              "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", 
              "up"
            ]
    links: 
      - db
  app:
    container_name: app-dev
    image: app-img-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ../.:/app
    ports:
      - 4000:8001

volumes:
   data: