version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-img-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../.:/app
    ports:
      - 4000:8001
